config/routes.rb
Rails.application.routes.draw do
  resources :special_prices
  resources :amenities
  get "rooms/unauthorized_rooms"
  get "rooms/my_rooms"
  resources :rooms
  devise_for :users, controllers: { confirmations: 'confirmations' }
  resources :cities
  resources :roles
  get "bookings/unconfirmed_bookings"
  resources :bookings
  root to: 'rooms#index'
  resources :reviews
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/special_price.rb
class SpecialPrice < ApplicationRecord
	belongs_to :room
	validates_presence_of :room_id, :start_date, :end_date, :price
	validate :check_date, on: :create

	def check_date
		if self.start_date < Date.today
			self.errors.add(:base, "your start date can't be past")
		elsif self.end_date < self.start_date
			self.errors.add(:base, "Your end date must be greaterthan start date")
		end
	end
end

app/controllers/special_prices_controller.rb
class SpecialPricesController < ApplicationController
  before_action :set_special_price, only: [:show, :edit, :update, :destroy]
      load_and_authorize_resource


  # GET /special_prices
  # GET /special_prices.json
  def index
    @special_prices = SpecialPrice.all
  end

  # GET /special_prices/1
  # GET /special_prices/1.json
  def show
  end

  # GET /special_prices/new
  def new
    @special_price = SpecialPrice.new
  end

  # GET /special_prices/1/edit
  def edit
  end

  # POST /special_prices
  # POST /special_prices.json
  def create
    @special_price = SpecialPrice.new(special_price_params)

    respond_to do |format|
      if @special_price.save
        format.html { redirect_to room_path(@special_price.room), notice: 'Special price was successfully created.' }
        format.json { render :show, status: :created, location: @special_price }
      else
        format.html { render :new }
        format.json { render json: @special_price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /special_prices/1
  # PATCH/PUT /special_prices/1.json
  def update
    respond_to do |format|
      if @special_price.update(special_price_params)
        format.html { redirect_to @special_price, notice: 'Special price was successfully updated.' }
        format.json { render :show, status: :ok, location: @special_price }
      else
        format.html { render :edit }
        format.json { render json: @special_price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /special_prices/1
  # DELETE /special_prices/1.json
  def destroy
    @special_price.destroy
    respond_to do |format|
      format.html { redirect_to special_prices_url, notice: 'Special price was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_special_price
      @special_price = SpecialPrice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def special_price_params
      params.require(:special_price).permit(:room_id, :start_date, :end_date, :price)
    end
end

app/helpers/special_prices_helper.rb
module SpecialPricesHelper
end

app/views/special_prices/_form.html.erb
<%= form_with(model: special_price, local: true) do |form| %>
  <% if special_price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(special_price.errors.count, "error") %> prohibited this special_price from being saved:</h2>

      <ul>
      <% special_price.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :room_id %>
    <%= form.number_field :room_id, id: :special_price_room_id %>
  </div>

  

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date, id: :special_price_start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date, id: :special_price_end_date %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :special_price_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/special_prices/edit.html.erb
<h1>Editing Special Price</h1>

<%= render 'form', special_price: @special_price %>

<%= link_to 'Show', @special_price %> |
<%= link_to 'Back', special_prices_path %>

app/views/special_prices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Special Prices</h1>

<table>
  <thead>
    <tr>
      <th>Room</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @special_prices.each do |special_price| %>
      <tr>
        <td><%= special_price.room_id %></td>
        <td><%= special_price.start_date %></td>
        <td><%= special_price.end_date %></td>
        <td><%= special_price.price %></td>
        <td><%= link_to 'Show', special_price %></td>
        <td><%= link_to 'Edit', edit_special_price_path(special_price) %></td>
        <td><%= link_to 'Destroy', special_price, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Special Price', new_special_price_path %>

app/views/special_prices/new.html.erb
<h1>New Special Price</h1>

<%= render 'form', special_price: @special_price %>

<%= link_to 'Back', special_prices_path %>

app/views/special_prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room:</strong>
  <%= @special_price.room_id %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @special_price.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @special_price.end_date %>
</p>

<p>
  <strong>Price:</strong>
  <%= @special_price.price %>
</p>

<%= link_to 'Edit', edit_special_price_path(@special_price) %> |
<%= link_to 'Back', special_prices_path %>