config/routes.rb
Rails.application.routes.draw do
  resources :special_prices
  resources :amenities
  get "rooms/unauthorized_rooms"
  get "rooms/my_rooms"
  resources :rooms
  devise_for :users, controllers: { confirmations: 'confirmations' }
  resources :cities
  resources :roles
  get "bookings/unconfirmed_bookings"
  resources :bookings
  root to: 'rooms#index'
  resources :reviews
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
	belongs_to :user
	belongs_to :city
	has_many :bookings
	has_many :reviews
	has_many :special_prices
	
	has_many :amenity_rooms
	has_many :amenities, through: :amenity_rooms
	validates_presence_of :name,:price,:rules,:image,:latitude,:longitude,:address,:description
	mount_uploader :image, CoverUploader
	before_validation :set_values
	before_create :update_guest_to_host



 	def update_guest_to_host 
   			self.user.update_attributes(role_id: Role.last.id)
 	end


	def set_values				
		response = HTTParty.get("https://maps.googleapis.com/maps/api/geocode/json?address=#{self.name}&key=AIzaSyDN5_FPsKTbM_46mqbW604jB7mulmtWZIM")
		has_json = JSON.parse(response.body)
							
			self.latitude = "#{has_json["results"][0]["geometry"]["location"]["lat"]}"
			self.longitude = "#{has_json["results"][0]["geometry"]["location"]["lng"]}"
			self.address = "#{has_json["results"][0]["formatted_address"]}"
			self.description = Faker::Lorem.paragraphs(1, true)
	end


	def self.search(term, current_page)
	  if term
	    page(current_page).where('name LIKE ?', "%#{term}%").order('id DESC')
	  else
	    page(current_page).order('id DESC') 
	  end
	end



	def self.search(term, page)
		  if term
		    where('name LIKE ?', "%#{term}%").paginate(page: page, per_page: 5).order('id DESC')
		  else
		    paginate(page: page, per_page: 5).order('id DESC') 
		  end
	end





end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
      before_action :authenticate_user!, except: [:index,:show]

  before_action :set_room, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.where("is_authorized = ?", true).order(price: :DESC).search(params[:term], params[:page])

  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @booking = Booking.new
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def unauthorized_rooms
    
      if current_user.role?("admin")
          @rooms = Room.where("is_authorized = ?",false)
          
      end
  end
  def my_rooms
    @rooms = current_user.rooms

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :description, :price, :rules, :address, :image, :latitude, :longitude, :city_id,:is_authorized, amenity_ids:[])
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :city_id %>
    <%= form.collection_select :city_id, City.all , :id , :name , prompt: "Select City"  %>
  </div>


  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :room_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :room_description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :room_price %>
  </div>



<h3>select Amenities </h3>
  <%= form.collection_check_boxes :amenity_ids, Amenity.all, :id, :name do |amenity|%>
  <p><%= amenity.label%> <%= amenity.check_box%> </p>
  
  <%end%>





  <div class="field">
    <%= form.label :rules %>
    <%= form.text_area :rules, id: :room_rules %>
  </div>

  
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :room_image %>
  </div>

  

  
  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Owner</th>
      <th>Address</th>
      
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%=link_to (image_tag (room.image ), size: "350x160"),room %></td>
        <td><%=link_to room.name,room %></td>
        <td><%= room.description %></td>
        <td><%= room.price %></td>
        <td><%= room.user.username %></td>
        <td><%= room.address %></td>
        <td><%= room.city.name %></td>
      <% if (user_signed_in?) && (can? :edit, room) %>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
      <%end%>
      <% if (user_signed_in?) && (can? :destroy, room) %>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if (user_signed_in?)%>

  <%= link_to 'New Room', new_room_path %>
  <%end%>

<div class="apple_pagination">
  <div class="page_info">
    <%= page_entries_info @rooms %>
  </div>
  <%= will_paginate @rooms, :container => false %>
</div>

app/views/rooms/my_rooms.html.erb
<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Rules</th>
      <th>Address</th>
      
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%=link_to (image_tag (room.image)),room %></td>
        <td><%=link_to room.name,room %></td>
        <td><%= room.description %></td>
        <td><%= room.price %></td>
        <td><%= room.rules %></td>
        <td><%= room.address %></td>
        <td><%= room.city.name %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p>
  <%= image_tag @room.image , size: "450x350" %>
</p>


<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @room.price %>
</p>




<p>
    <%= form_for @booking do |f| %>
    <p>Check In :<%= f.date_select :start_date%></p>
    <p>Check Out: <%= f.date_select :end_date%></p>
    <%=  f.hidden_field :room_id, value: @room.id%>
    <%= f.submit "Request to Book"%>

    <%end%>

</p>

      <% if (user_signed_in?) && (current_user.id == @room.user.id) %>

<h3>Add Special Price</h3>

<p>
    <%= form_for SpecialPrice.new do |f| %>
    <p>Start date :<%= f.date_select :start_date%></p>
    <p> End date: <%= f.date_select :end_date%></p>
    <%=  f.hidden_field :room_id, value: @room.id%>
    <p>SpecialPrice:<%= f.text_field :price%></p>
    <%= f.submit "Add Price"%>

    <%end%>

</p>
<%end%>




<p>
  <strong>Address:</strong>
  <%= @room.address %>
</p>





<p>
  <strong>Description:</strong>
  <%= @room.description %>
</p>


<p>
  <strong>Amenities:</strong>
  <ul>
  <% @room.amenities.each do |amenity|  %>

  <li><%= amenity.name %></li>
  <%end%>
</ul>

</p>


<p>
  <strong>Rules:</strong>
  <%= @room.rules %>
</p>


<p>
  <strong>Latitude:</strong>
  <%= @room.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @room.longitude %>
</p>

<p>
  <strong>City:</strong>
  <%= @room.city.name %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @room.user.username %>

</p>
<h2>Listing other rooms of (<%=@room.user.username%>) </h2>
  
<% @room.user.rooms.each do |room| %>
  <%unless @room.id == room.id %>
     <li><%= image_tag room.image , size: "50x50" %><%=link_to room.name, room_path(room) %></li>

    <%end%>
<%end%>

<h2> Reviews</h2>

<%if @room.reviews.empty?%>
<p>No reviews found ! </p>
<%else%>
<h3>Listing Reviews</h3>
<ol>
    <%@room.reviews.each do |review|%>
    <li>
        <%=link_to review.review, review_path(review) %> -  - <%=review.user.username%>
        <%if (user_signed_in?) && (can? :update, review)%>
        <%= link_to "destroy" , review_path(review.id), method: :delete, data: {confirm: "Are you sure you want to delete review "}%> | <%= link_to "Edit", edit_review_path(review.id)%> 
    </li>
        <%end%>
    <%end%>
</ol>
<%end%>



   




 <% if (user_signed_in?) && (current_user.id == @room.user.id) %>


<%= link_to 'Edit', edit_room_path(@room) %>
<%end%> |
<%= link_to 'Back', rooms_path %>


<p>
<iframe
  width="500"
  height="350"
  frameborder="10" style="border:20"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAX2sQ4tAAnRSwl5r25NyPSfdgUo5CSBPM
    &q= <%= @room.latitude%>,<%= @room.longitude %>" allowfullscreen>
</iframe>
</p>

app/views/rooms/unauthorized_rooms.html.erb
<% if @rooms.empty? %>
  <h2>No Rooms Found</h2>
<% else %>
  <h2>Listing Unauthorized Rooms</h2>
  <ul>
    <% @rooms.each do |room| %>
      <li>
        <p> Name : <%= room.name %> </p>
        <p> Is_Authorized : <%= room.is_authorized %> </p>
        <p> Room Owner : <%= room.user.username %> </p>

        <p>
          <%= form_for room do |f| %>
            <%= f.hidden_field :is_authorized, value: true %>
            <%= f.submit "Authorize Room"%>
          <% end %>
        </p>
        <p><%= link_to "Show", room_path(room.id) %></p>
        <%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %>
      </li>
    <% end %>
  </ul>
<% end %>