config/routes.rb
Rails.application.routes.draw do
  resources :special_prices
  resources :amenities
  get "rooms/unauthorized_rooms"
  get "rooms/my_rooms"
  resources :rooms
  devise_for :users, controllers: { confirmations: 'confirmations' }
  resources :cities
  resources :roles
  get "bookings/unconfirmed_bookings"
  resources :bookings
  root to: 'rooms#index'
  resources :reviews
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rentaroom</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  
    <style>

      body {
          background: url("../image1.jpg");
          background-size:cover;
          background-repeat: no-repeat;
          width: 99%;
      }
    </style>


  <body>
  <h2>
       <% if user_signed_in? %> 
            welcome <%= current_user.username.capitalize %> &
            Your are <%= current_user.role.name.upcase%>!
            <%= link_to "Account Setting", edit_user_registration_path %>
              | <%= link_to "Logout", destroy_user_session_path, method: :delete %> 

              | <%= link_to "cities" , cities_path%>
            <% if (user_signed_in?) && (current_user.role? "admin") %>
                          | <%= link_to "Amenities", amenities_path %>

              | <%= link_to "Unauthorized_rooms", rooms_unauthorized_rooms_path %>
            <% end%>
            <% if (user_signed_in?) && (current_user.role? "host") %>

              | <%= link_to "Unconfirmed_bookings", bookings_unconfirmed_bookings_path %>
              <%end%>
              | <%= link_to "My Rooms", rooms_my_rooms_path%>
              | <%= link_to "My Bookings", bookings_path%>
      <% else %>
            <%= link_to "Register", new_user_registration_path %> 
            | <%= link_to "Login", new_user_session_path %> 
      <% end %>

        | <%= link_to "Rooms", rooms_path %> 
        
          <br/>

</h2>

         <%= notice %>
    <%= yield %>
  </body>
</html>